version: '3'
services:
  jenkins:
    build:
      context: ./dockerfiles
      dockerfile: Dockerfile-jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
    networks:
      - jenkins

networks:
  jenkins:
    driver: bridge

volumes:
  jenkins_home:
