# Use an official Python runtime based on Alpine 3.17 as the base image.
FROM python:3.10-alpine3.17

# Set the working directory inside the container to "/app".
WORKDIR /app

# Copy 'app.py', 'templates' directory and 'requirements.txt' from the local directory to the "/app" directory in the container.
COPY ./app/app.py /app/
COPY ./app/templates /app/templates
COPY ./app/requirements.txt /app/

# Install necessary Alpine packages for building certain Python packages
RUN apk add --no-cache gcc musl-dev linux-headers

# Install any packages specified in 'requirements.txt'.
RUN pip3 install -r requirements.txt

# Run 'python3 app.py' when the container launches.
CMD ["python3", "app.py"]

# Expose port 5000 to interact with the application.
EXPOSE 5000
